spring:
  datasource:
    username: root
    password: 123456
    #url: jdbc:mysql://49.234.54.34:3306/mydb
    url: jdbc:mysql://localhost:3306/mydb
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      max-lifetime: 30000
      connection-test-query: SELECT 1
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE

  redis:
    host: 127.0.0.1
    #host: 49.234.54.34
    port: 6379
    #password: Nju123456
    timeout: 60s



  kafka:
    consumer:
      group-id: foo
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      #bootstrap-servers: 49.234.54.34:9092
    producer:
      acks: all
      bootstrap-servers: localhost:9092
      #bootstrap-servers: 49.234.54.34:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    listener:
      missing-topics-fatal: false
server:
  port: 8088
